# Generated by Django 6.0.4 on 2026-04-24 09:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], db_index=True, max_length=20)),
                ('grams', models.DecimalField(decimal_places=2, help_text='Consumed quantity in grams.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('5000.00'))])),
                ('consumed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_name', models.CharField(editable=False, max_length=255)),
                ('calories', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('carbs', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('fat', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_logs', to='food.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-consumed_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'consumed_at'], name='tracking_me_user_id_ca5029_idx'), models.Index(fields=['user', 'meal_type', 'consumed_at'], name='tracking_me_user_id_625f83_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('grams__gt', 0)), name='tracking_meal_grams_gt_zero')],
            },
        ),
    ]
