# Generated by Django 6.0.4 on 2026-04-23 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories_per_100g', models.FloatField()),
                ('protein_per_100g', models.FloatField()),
                ('carbs_per_100g', models.FloatField()),
                ('fat_per_100g', models.FloatField()),
                ('default_serving_size', models.FloatField(blank=True, null=True)),
                ('serving_name', models.CharField(blank=True, max_length=50, null=True)),
                ('fiber_per_100g', models.FloatField(blank=True, null=True)),
                ('sugar_per_100g', models.FloatField(blank=True, null=True)),
                ('is_indian', models.BooleanField(default=True)),
                ('is_veg', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.foodcategory')),
            ],
        ),
    ]
